BEGIN;

DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS appointments CASCADE;
DROP TABLE IF EXISTS mentors CASCADE;

CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(100) NOT NULL UNIQUE,
  password VARCHAR(100) NOT NULL,
  date_created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE mentors (
  id SERIAL PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(100) NOT NULL UNIQUE,
  description TEXT NOT NULL,
  img_url VARCHAR NOT NULL,
  date_created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE appointments (
  id SERIAL PRIMARY KEY,
  user_id INTEGER REFERENCES users(id) NOT NULL,
  mentor_id INTEGER REFERENCES mentors(id) NOT NULL,
  date_and_time TIMESTAMP NOT NULL,
  topics TEXT[] NOT NULL, 
  info TEXT,
  chat_string VARCHAR(6) NOT NULL, 
  date_created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);



COMMIT;
